# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture_pic',
            new_name='profile_pics',
        ),
    ]
